version: 1.1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VS_VERSION: 12 2013
    VS_PLATFORM: win32
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VS_VERSION: 12 2013
    VS_PLATFORM: x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VS_VERSION: 14 2015
    VS_PLATFORM: win32
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VS_VERSION: 14 2015
    VS_PLATFORM: x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS_VERSION: 15 2017
    VS_PLATFORM: win32
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS_VERSION: 15 2017
    VS_PLATFORM: x64

before_build:
  - git submodule update --init --recursive
  - echo Running cmake...
  - cmake . -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: brynet.sln
  parallel: true
  verbosity: minimal

test_script:
    - cd tests
    - ctest -V -C %CONFIGURATION%